"""add roadmap save fields

Revision ID: 4cd94df6fdf8
Revises: 8345131fc80a
Create Date: 2026-01-26 06:51:17.026517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd94df6fdf8'
down_revision: Union[str, Sequence[str], None] = '8345131fc80a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap', sa.Column('name', sa.String(), nullable=True))
    op.add_column('roadmap', sa.Column('career_goal', sa.String(), nullable=True))
    op.add_column('roadmap', sa.Column('roadmap_data', sa.JSON(), nullable=True))
    op.alter_column('roadmap', 'class_level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roadmap', 'class_level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('roadmap', 'roadmap_data')
    op.drop_column('roadmap', 'career_goal')
    op.drop_column('roadmap', 'name')
    # ### end Alembic commands ###
