"""add chatconversations table

Revision ID: 8345131fc80a
Revises: e426de71f7ae
Create Date: 2026-01-21 16:53:17.171850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8345131fc80a'
down_revision: Union[str, Sequence[str], None] = 'e426de71f7ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatconversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionid', sa.String(length=100), nullable=False),
    sa.Column('useremail', sa.String(length=255), nullable=True),
    sa.Column('userquery', sa.Text(), nullable=False),
    sa.Column('botresponse', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON(), nullable=True),
    sa.Column('ragscore', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('responsetype', sa.String(length=50), nullable=False),
    sa.Column('responsetime', sa.Float(), nullable=True),
    sa.Column('upvoted', sa.Boolean(), nullable=True),
    sa.Column('feedbacktext', sa.Text(), nullable=True),
    sa.Column('createdat', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatconversations_id'), 'chatconversations', ['id'], unique=False)
    op.create_index(op.f('ix_chatconversations_sessionid'), 'chatconversations', ['sessionid'], unique=False)
    op.create_index(op.f('ix_chatconversations_useremail'), 'chatconversations', ['useremail'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chatconversations_useremail'), table_name='chatconversations')
    op.drop_index(op.f('ix_chatconversations_sessionid'), table_name='chatconversations')
    op.drop_index(op.f('ix_chatconversations_id'), table_name='chatconversations')
    op.drop_table('chatconversations')
    # ### end Alembic commands ###
