"""add_entrance_exam_tables

Revision ID: e426de71f7ae
Revises: e749fa088195
Create Date: 2026-01-20 16:01:02.041024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e426de71f7ae'
down_revision: Union[str, Sequence[str], None] = 'e749fa088195'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrance_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_name', sa.String(length=100), nullable=False),
    sa.Column('exam_full_name', sa.String(length=300), nullable=True),
    sa.Column('conducting_body', sa.String(length=200), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=True),
    sa.Column('registration_start_date', sa.Date(), nullable=True),
    sa.Column('registration_end_date', sa.Date(), nullable=True),
    sa.Column('exam_pattern', sa.String(length=100), nullable=True),
    sa.Column('official_website', sa.String(length=500), nullable=True),
    sa.Column('syllabus_link', sa.String(length=500), nullable=True),
    sa.Column('academic_year', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrance_exams_exam_name'), 'entrance_exams', ['exam_name'], unique=True)
    op.create_index(op.f('ix_entrance_exams_id'), 'entrance_exams', ['id'], unique=False)
    op.create_table('college_entrance_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('college_name', sa.String(length=300), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('entrance_exam_id', sa.Integer(), nullable=False),
    sa.Column('cutoff_rank', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entrance_exam_id'], ['entrance_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_college_entrance_mappings_branch'), 'college_entrance_mappings', ['branch'], unique=False)
    op.create_index(op.f('ix_college_entrance_mappings_college_name'), 'college_entrance_mappings', ['college_name'], unique=False)
    op.create_index(op.f('ix_college_entrance_mappings_degree'), 'college_entrance_mappings', ['degree'], unique=False)
    op.create_index(op.f('ix_college_entrance_mappings_id'), 'college_entrance_mappings', ['id'], unique=False)
    op.create_table('exam_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=300), nullable=False),
    sa.Column('entrance_exam_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('alert_date', sa.Date(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.Column('college_name', sa.String(length=300), nullable=True),
    sa.Column('degree', sa.String(length=100), nullable=True),
    sa.Column('branch', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['entrance_exam_id'], ['entrance_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_alerts_id'), 'exam_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_exam_alerts_is_sent'), 'exam_alerts', ['is_sent'], unique=False)
    op.create_index(op.f('ix_exam_alerts_user_email'), 'exam_alerts', ['user_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exam_alerts_user_email'), table_name='exam_alerts')
    op.drop_index(op.f('ix_exam_alerts_is_sent'), table_name='exam_alerts')
    op.drop_index(op.f('ix_exam_alerts_id'), table_name='exam_alerts')
    op.drop_table('exam_alerts')
    op.drop_index(op.f('ix_college_entrance_mappings_id'), table_name='college_entrance_mappings')
    op.drop_index(op.f('ix_college_entrance_mappings_degree'), table_name='college_entrance_mappings')
    op.drop_index(op.f('ix_college_entrance_mappings_college_name'), table_name='college_entrance_mappings')
    op.drop_index(op.f('ix_college_entrance_mappings_branch'), table_name='college_entrance_mappings')
    op.drop_table('college_entrance_mappings')
    op.drop_index(op.f('ix_entrance_exams_id'), table_name='entrance_exams')
    op.drop_index(op.f('ix_entrance_exams_exam_name'), table_name='entrance_exams')
    op.drop_table('entrance_exams')
    # ### end Alembic commands ###
